"use client";
import Link from "next/link"; import { useState } from "react"; import styles from "./review.module.css";
declare global { interface Window { Razorpay: new (options: Record<string, unknown>) => { open: () => void } } }
function loadRazorpay() { return new Promise<boolean>((resolve) => { if (window.Razorpay) return resolve(true); const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.async = true; script.onload = () => resolve(true); script.onerror = () => resolve(false); document.body.appendChild(script); }); }
export function RazorpayCheckoutButton({ amount, orderId, ready }: { amount: string; orderId: string; ready: boolean }) {
  const [accepted,setAccepted]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  async function pay() { if (!accepted || busy || !ready) return; setBusy(true); setMessage(""); if (!await loadRazorpay()) { setBusy(false); setMessage("Secure checkout could not load."); return; }
    try { const response = await fetch("/api/payments/razorpay/order", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({orderId,termsAccepted:true}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error);
      const checkout = new window.Razorpay({ key:data.keyId, amount:data.amount, currency:"INR", name:"M'ma Organic Farm", description:"Farm order", order_id:data.providerOrderId, prefill:data.prefill, theme:{color:"#f4c84a"}, modal:{ondismiss:()=>{setBusy(false);setMessage("Payment was not completed. Your order is saved.");}}, handler:async (result: Record<string,string>)=>{ setMessage("Confirming your payment…"); const verified=await fetch("/api/payments/razorpay/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId,paymentId:result.razorpay_payment_id,providerOrderId:result.razorpay_order_id,signature:result.razorpay_signature})}); const confirmation=await verified.json(); if(!verified.ok){setBusy(false);setMessage(confirmation.error ?? "Confirmation is pending. Do not pay again.");return;} window.location.assign(`/checkout/success?order=${orderId}`);}}); checkout.open();
    } catch(error) { setBusy(false); setMessage(error instanceof Error ? error.message : "Payment could not start."); }
  }
  return <div className={styles.checkout}><label><input type="checkbox" checked={accepted} disabled={!ready||busy} onChange={(event)=>setAccepted(event.target.checked)}/><span>I agree to the <Link href="/terms">Terms</Link> and <Link href="/cancellation-refunds">cancellation policy</Link>.</span></label><button type="button" disabled={!accepted||busy||!ready} onClick={pay}>{busy?"Opening secure payment…":`Pay ${amount}`}</button>{!ready&&<p className={styles.setup}>Online payment is prepared but not yet enabled in this preview.</p>}{message&&<p className={styles.message}>{message}</p>}</div>;
}
